### ISSUE TITLE
Questions about the code structure

### ISSUE THREAD

**Issue by CUHKSZzxy** [opengear-project/GEAR#10]
Thanks for your excellent work!

I am a little bit confused about the code structure and their usages:

    GEARLM/GEARLM
        -- Simulated
        -- TrueCompression
            -- models
            -- old_models

What's the difference between Simulated and TrueCompression, and their usages respectively?
And what's the difference between models and old_models?

Any help would be appreciated!

**Comment by HaoKang-Timmy** [comment]
We are now refining the algorithm and probably new results will come out next week with reproducable code.

**Comment by shhn1** [comment]
@HaoKang-Timmy  Hello, are there any updates? : )

**Comment by HaoKang-Timmy** [comment]
> @HaoKang-Timmy Hello, are there any updates? : )

Yes, we have updated the new code. And baseline on arxiv will be changed accordingly
