### ISSUE TITLE
How to reproduce GEAR on Mistral models

### ISSUE THREAD

**Issue by CUHKSZzxy** [opengear-project/GEAR#12]
Thanks for your excellent work!

May I ask for the scripts and examples to reproduce GEAR results on MMLU, using Mistral models? It is difficult for me to find related scripts and the usage of different configuration / parameters.

**Comment by HaoKang-Timmy** [comment]
We have updated sh files to run llama models on Aqua,GSM8k and BBH datasets

**Comment by CUHKSZzxy** [comment]
Thanks for your reply, but my concern is how to reproduce results on **Mistral** models, thanks!
