### ISSUE TITLE
Where is the outlier extraction logic in `cuda_support_gear`

### ISSUE THREAD

**Issue by Ther-nullptr** [opengear-project/GEAR#13]
Hello, I have read the paper of `GEAR`, and read the code of `cuda_support_gear` part. I wanna ask where is the "outlier extraction" logic in cuda/triton? I only see the quantization and error correlation in the [code](https://github.com/opengear-project/GEAR/blob/main/cuda_supported_gear/modeling_llamagear.py#L23C1-L37C104).

**Comment by HaoKang-Timmy** [comment]
"outlier extraction" cuda kernel will be added soon. Now the cuda supported code is only for GEAR-L.
