### ISSUE TITLE
Compatibility of requirements.txt with x86_64 architecture

### ISSUE THREAD

**Issue by DKmiyan** [opengear-project/GEAR#18]
Hello,

I've noticed that the requirements.txt file for this repository appears to be tailored for the aarch64 architecture. I'm currently using an x86_64 machine and I'm interested in running the GenerationBench content from this repository.

Could you please confirm if it's possible to run this code on an x86_64 architecture? Additionally, if it requires modifications, such as removing packages like cudf and cugraph which do not have x86_64 versions, would the rest of the GenerationBench functionality still operate correctly?

**Comment by YEOMJINSEOP** [comment]
Hi, Did you figure it out?
