### ISSUE TITLE
questions about rapids folder

### ISSUE THREAD

**Issue by hzfengfengxia** [opengear-project/GEAR#3]
I saw that some packages in the requirements.txt are installed via local .whl files, especially in the folder named rapids. However, I have not found this rapids folder. How should I solve this problem?

**Comment by HaoKang-Timmy** [comment]
I will modify them.
Currently I suggest you install transformers and GEARLM at the newest version. And then it may run.

**Comment by hzfengfengxia** [comment]
> I will modify them. Currently I suggest you install transformers and GEARLM at the newest version. And then it may run.

thankyou！
