### ISSUE TITLE
[Bug] maybe a bug in fake_quant_error_simulation function

### ISSUE THREAD

**Issue by HarryWu-CHN** [opengear-project/GEAR#5]
https://github.com/opengear-project/GEAR/blob/79ad3fcdb528fceaf605923479fe14fdf3953ffd/TrueCompressionLlaMA/models/TrueCompressFunction.py#L128

`error = input - torch.round((input - min) / step)`

but it should be `error = input - (torch.round((input - min) / step) * step + min)`. So that the `error` is the quantization residuals.

**Comment by HaoKang-Timmy** [comment]
Thanks for reminding us. We have fixed this error in our new version with fused quantized operator support. Will upload soon.
