### ISSUE TITLE
How to eval GEAR with lm-eval framework?

### ISSUE THREAD

**Issue by ThisisBillhe** [opengear-project/GEAR#6]
Hi Hao Kang, sorry to interrupt. I see there is a lm-harness dir, however I can not find a script or guide on how to evaluate GEAR with lm_eval. Am I missing something?

**Comment by HaoKang-Timmy** [comment]
Please look at this.
I am currently updating kernel support for GEAR so the whole guidance will be refined in future.
https://github.com/opengear-project/GEAR/blob/main/lm-harness/shfile_example.sh

**Comment by HaoKang-Timmy** [comment]
Done
