### ISSUE TITLE
Qustion about storage

### ISSUE THREAD

**Issue by mlxht990720** [opengear-project/GEAR#7]
Thanks for your great work and the open-sourced code！
I have some problems with the storage of sparse matrix S. Could you please provide the code to reproduce the memory size results of KV cache in your paper? 
Thanks a lot!!!

**Comment by HaoKang-Timmy** [comment]
Hi, we do not need to store a whole S matrix instead we store outliers' index and value. Please refer to 
[here](https://github.com/opengear-project/GEAR/blob/main/TrueCompressionLlaMA/old_models/CompressUtils/TrueCompressFunction.py)
for more details.

**Comment by mlxht990720** [comment]
Got it! Thank u very much!
I still have another question, when I reproduce the accurancy results in table 1 on GSM8K, no matter how I change the configs like compression method or quantization bit, the accurancy result remains the same. Have I missed some instructions?

**Comment by HaoKang-Timmy** [comment]
> Got it! Thank u very much! I still have another question, when I reproduce the accurancy results in table 1 on GSM8K, no matter how I change the configs like compression method or quantization bit, the accurancy result remains the same. Have I missed some instructions?

Can you try with the new code. I guess there is no problem now.

**Comment by mlxht990720** [comment]
Thank u very much.
