### ISSUE TITLE
Question about the shell commands details on how to reproduce the main results of COT and zeroshot performance

### ISSUE THREAD

**Issue by zoominguniverse** [opengear-project/GEAR#9]
I am a totally freshman on huggingface,but i succeed in configuring the environments and run successfully the GenerationBench/GenerationTest/run.sh.Can u give all the python commands when eval the main results of COT and zeroshot performance?

**Comment by HaoKang-Timmy** [comment]
Sure, I am now renewing the github repo and before next two weeek the new version should be released and it will provide very detailed guidance.

**Comment by HaoKang-Timmy** [comment]
Done
